# 小彭的乱码
file_one = open('test', 'rb+')
file_two = open('readme1', 'r+', encoding='utf-8')
text_one = file_one.read()
text_two = file_two.read()
print(text_one)
print(text_two)
file_one.write('\n机器学习'.encode('utf-8'))
file_two.write('\n机器学习')
file_one.seek(0)
file_two.seek(0)
text_one = file_one.read()
text_two = file_two.read()
print(text_one)
print(text_two)